import logging
import os
import secrets
import string
from datetime import datetime, timedelta, timezone

import azure.functions as func
from azure.identity import AzureCliCredential
from azure.keyvault.secrets import SecretClient

from azure.communication.email import EmailClient


app = func.FunctionApp()


@app.timer_trigger(
    schedule="0 */5 * * * *",
    arg_name="mytimer",
    run_on_startup=True,
)
def RotateSecret(mytimer: func.TimerRequest) -> None:

    logging.info("===================================")
    logging.info("Azure Secret Rotation Started")
    logging.info("===================================")

    # Environment Variables

    key_vault_name = os.environ["KEY_VAULT_NAME"]

    communication_connection = os.environ["COMMUNICATION_SERVICES_CONNECTION_STRING"]

    sender = os.environ["EMAIL_SENDER"]

    recipient = os.environ["EMAIL_RECIPIENT"]

    # Connect to Key Vault

    credential = AzureCliCredential()

    vault_url = f"https://{key_vault_name}.vault.azure.net"

    client = SecretClient(
        vault_url=vault_url,
        credential=credential,
    )

    secret_name = "DatabasePassword"

    secret = client.get_secret(secret_name)

    logging.info(f"Secret Name: {secret.name}")

    # Check Expiry

    if secret.properties.expires_on is None:
        logging.warning("Secret has no expiration date.")
        return

    expires = secret.properties.expires_on

    remaining_days = (expires - datetime.now(timezone.utc)).days

    logging.info(f"Secret expires in {remaining_days} days.")

    if remaining_days > 30:
        logging.info("Secret is healthy.")
        return

    logging.info("Secret is nearing expiration.")
    logging.info("Generating new password...")

    # Generate Password

    alphabet = (
        string.ascii_letters +
        string.digits +
        "!@#$%^&*"
    )

    new_password = "".join(
        secrets.choice(alphabet)
        for _ in range(32)
    )

    new_expiry = datetime.now(timezone.utc) + timedelta(days=365)

    # Update Key Vault

    client.set_secret(
        secret_name,
        new_password,
        expires_on=new_expiry,
    )

    logging.info("===================================")
    logging.info("SECRET ROTATED SUCCESSFULLY")
    logging.info(f"New Expiry: {new_expiry}")
    logging.info("===================================")

    # Send Email

    logging.info("Sending email notification...")

    try:

        email_client = EmailClient.from_connection_string(
            communication_connection
        )

        message = {
            "senderAddress": sender,
            "recipients": {
                "to": [
                    {
                        "address": recipient
                    }
                ]
            },
            "content": {
                "subject": "Azure Key Vault Secret Rotated",
                "plainText": f"""
Hello,

The secret '{secret_name}' has been rotated successfully.

Key Vault:
{key_vault_name}

New Expiration:
{new_expiry}

This email was automatically generated by the Azure Secret Rotation Pipeline.

Regards,
Azure Function
""",
                "html": f"""
<html>
<body>

<h2>Azure Secret Rotation</h2>

<p>Your Key Vault secret was rotated successfully.</p>

<ul>
<li><b>Secret:</b> {secret_name}</li>
<li><b>Key Vault:</b> {key_vault_name}</li>
<li><b>New Expiration:</b> {new_expiry}</li>
</ul>

<p>This notification was generated automatically.</p>

</body>
</html>
"""
            }
        }

        poller = email_client.begin_send(message)

        result = poller.result()

        logging.info(f"Email Status: {result['status']}")

    except Exception as ex:

        logging.exception("Email sending failed")

        logging.exception(ex)

    logging.info("Azure Secret Rotation Finished")
